// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eol.maintenance.domain;

import com.eol.maintenance.domain.BuildLayer;
import com.eol.maintenance.domain.BuildLayerDataOnDemand;
import com.eol.maintenance.domain.SoftwareVersion;
import com.eol.maintenance.domain.SoftwareVersionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect BuildLayerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BuildLayerDataOnDemand: @Component;
    
    private Random BuildLayerDataOnDemand.rnd = new SecureRandom();
    
    private List<BuildLayer> BuildLayerDataOnDemand.data;
    
    @Autowired
    SoftwareVersionDataOnDemand BuildLayerDataOnDemand.softwareVersionDataOnDemand;
    
    public BuildLayer BuildLayerDataOnDemand.getNewTransientBuildLayer(int index) {
        BuildLayer obj = new BuildLayer();
        setDescription(obj, index);
        setHelpFile(obj, index);
        setIdx(obj, index);
        setLive(obj, index);
        setName(obj, index);
        setRequired(obj, index);
        setSoftwareVersion(obj, index);
        setUuid(obj, index);
        return obj;
    }
    
    public void BuildLayerDataOnDemand.setDescription(BuildLayer obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void BuildLayerDataOnDemand.setHelpFile(BuildLayer obj, int index) {
        String helpFile = "helpFile_" + index;
        obj.setHelpFile(helpFile);
    }
    
    public void BuildLayerDataOnDemand.setIdx(BuildLayer obj, int index) {
        Long idx = new Integer(index).longValue();
        obj.setIdx(idx);
    }
    
    public void BuildLayerDataOnDemand.setLive(BuildLayer obj, int index) {
        Boolean live = Boolean.TRUE;
        obj.setLive(live);
    }
    
    public void BuildLayerDataOnDemand.setName(BuildLayer obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void BuildLayerDataOnDemand.setRequired(BuildLayer obj, int index) {
        Boolean required = Boolean.TRUE;
        obj.setRequired(required);
    }
    
    public void BuildLayerDataOnDemand.setSoftwareVersion(BuildLayer obj, int index) {
        SoftwareVersion softwareVersion = softwareVersionDataOnDemand.getRandomSoftwareVersion();
        obj.setSoftwareVersion(softwareVersion);
    }
    
    public void BuildLayerDataOnDemand.setUuid(BuildLayer obj, int index) {
        Long uuid = new Integer(index).longValue();
        obj.setUuid(uuid);
    }
    
    public BuildLayer BuildLayerDataOnDemand.getSpecificBuildLayer(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        BuildLayer obj = data.get(index);
        Long id = obj.getId();
        return BuildLayer.findBuildLayer(id);
    }
    
    public BuildLayer BuildLayerDataOnDemand.getRandomBuildLayer() {
        init();
        BuildLayer obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return BuildLayer.findBuildLayer(id);
    }
    
    public boolean BuildLayerDataOnDemand.modifyBuildLayer(BuildLayer obj) {
        return false;
    }
    
    public void BuildLayerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = BuildLayer.findBuildLayerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'BuildLayer' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<BuildLayer>();
        for (int i = 0; i < 10; i++) {
            BuildLayer obj = getNewTransientBuildLayer(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
