// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eol.maintenance.domain;

import com.eol.maintenance.domain.SMMGroupIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SMMGroupIntegrationTest_Roo_Configurable {
    
    declare @type: SMMGroupIntegrationTest: @Configurable;
    
}
