// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eol.maintenance.domain;

import com.eol.maintenance.domain.SMMLine;
import com.eol.maintenance.domain.SMMLineDataOnDemand;
import com.eol.maintenance.domain.SMMLineIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SMMLineIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SMMLineIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SMMLineIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SMMLineIntegrationTest: @Transactional;
    
    @Autowired
    SMMLineDataOnDemand SMMLineIntegrationTest.dod;
    
    @Test
    public void SMMLineIntegrationTest.testCountSMMLines() {
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to initialize correctly", dod.getRandomSMMLine());
        long count = SMMLine.countSMMLines();
        Assert.assertTrue("Counter for 'SMMLine' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SMMLineIntegrationTest.testFindSMMLine() {
        SMMLine obj = dod.getRandomSMMLine();
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to provide an identifier", id);
        obj = SMMLine.findSMMLine(id);
        Assert.assertNotNull("Find method for 'SMMLine' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SMMLine' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SMMLineIntegrationTest.testFindAllSMMLines() {
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to initialize correctly", dod.getRandomSMMLine());
        long count = SMMLine.countSMMLines();
        Assert.assertTrue("Too expensive to perform a find all test for 'SMMLine', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SMMLine> result = SMMLine.findAllSMMLines();
        Assert.assertNotNull("Find all method for 'SMMLine' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SMMLine' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SMMLineIntegrationTest.testFindSMMLineEntries() {
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to initialize correctly", dod.getRandomSMMLine());
        long count = SMMLine.countSMMLines();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SMMLine> result = SMMLine.findSMMLineEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SMMLine' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SMMLine' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SMMLineIntegrationTest.testFlush() {
        SMMLine obj = dod.getRandomSMMLine();
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to provide an identifier", id);
        obj = SMMLine.findSMMLine(id);
        Assert.assertNotNull("Find method for 'SMMLine' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySMMLine(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SMMLine' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SMMLineIntegrationTest.testMergeUpdate() {
        SMMLine obj = dod.getRandomSMMLine();
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to provide an identifier", id);
        obj = SMMLine.findSMMLine(id);
        boolean modified =  dod.modifySMMLine(obj);
        Integer currentVersion = obj.getVersion();
        SMMLine merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SMMLine' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SMMLineIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to initialize correctly", dod.getRandomSMMLine());
        SMMLine obj = dod.getNewTransientSMMLine(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SMMLine' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SMMLine' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SMMLineIntegrationTest.testRemove() {
        SMMLine obj = dod.getRandomSMMLine();
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SMMLine' failed to provide an identifier", id);
        obj = SMMLine.findSMMLine(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SMMLine' with identifier '" + id + "'", SMMLine.findSMMLine(id));
    }
    
}
