// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eol.maintenance.domain;

import com.eol.maintenance.domain.SoftwareVersion;
import com.eol.maintenance.domain.SoftwareVersionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SoftwareVersionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SoftwareVersionDataOnDemand: @Component;
    
    private Random SoftwareVersionDataOnDemand.rnd = new SecureRandom();
    
    private List<SoftwareVersion> SoftwareVersionDataOnDemand.data;
    
    public SoftwareVersion SoftwareVersionDataOnDemand.getNewTransientSoftwareVersion(int index) {
        SoftwareVersion obj = new SoftwareVersion();
        setCurrentVersion(obj, index);
        setDtype(obj, index);
        setIncompleteVersion(obj, index);
        setMajorVersion(obj, index);
        setMinorVersion(obj, index);
        setUuid(obj, index);
        return obj;
    }
    
    public void SoftwareVersionDataOnDemand.setCurrentVersion(SoftwareVersion obj, int index) {
        Boolean currentVersion = Boolean.TRUE;
        obj.setCurrentVersion(currentVersion);
    }
    
    public void SoftwareVersionDataOnDemand.setDtype(SoftwareVersion obj, int index) {
        String dtype = "dtype_" + index;
        if (dtype.length() > 31) {
            dtype = dtype.substring(0, 31);
        }
        obj.setDtype(dtype);
    }
    
    public void SoftwareVersionDataOnDemand.setIncompleteVersion(SoftwareVersion obj, int index) {
        Boolean incompleteVersion = Boolean.TRUE;
        obj.setIncompleteVersion(incompleteVersion);
    }
    
    public void SoftwareVersionDataOnDemand.setMajorVersion(SoftwareVersion obj, int index) {
        Integer majorVersion = new Integer(index);
        obj.setMajorVersion(majorVersion);
    }
    
    public void SoftwareVersionDataOnDemand.setMinorVersion(SoftwareVersion obj, int index) {
        Integer minorVersion = new Integer(index);
        obj.setMinorVersion(minorVersion);
    }
    
    public void SoftwareVersionDataOnDemand.setUuid(SoftwareVersion obj, int index) {
        Long uuid = new Integer(index).longValue();
        obj.setUuid(uuid);
    }
    
    public SoftwareVersion SoftwareVersionDataOnDemand.getSpecificSoftwareVersion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SoftwareVersion obj = data.get(index);
        Long id = obj.getId();
        return SoftwareVersion.findSoftwareVersion(id);
    }
    
    public SoftwareVersion SoftwareVersionDataOnDemand.getRandomSoftwareVersion() {
        init();
        SoftwareVersion obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SoftwareVersion.findSoftwareVersion(id);
    }
    
    public boolean SoftwareVersionDataOnDemand.modifySoftwareVersion(SoftwareVersion obj) {
        return false;
    }
    
    public void SoftwareVersionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SoftwareVersion.findSoftwareVersionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SoftwareVersion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SoftwareVersion>();
        for (int i = 0; i < 10; i++) {
            SoftwareVersion obj = getNewTransientSoftwareVersion(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
