// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eol.maintenance.domain;

import com.eol.maintenance.domain.SoftwareVersion;
import com.eol.maintenance.domain.SoftwareVersionDataOnDemand;
import com.eol.maintenance.domain.SoftwareVersionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SoftwareVersionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SoftwareVersionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SoftwareVersionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SoftwareVersionIntegrationTest: @Transactional;
    
    @Autowired
    SoftwareVersionDataOnDemand SoftwareVersionIntegrationTest.dod;
    
    @Test
    public void SoftwareVersionIntegrationTest.testCountSoftwareVersions() {
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to initialize correctly", dod.getRandomSoftwareVersion());
        long count = SoftwareVersion.countSoftwareVersions();
        Assert.assertTrue("Counter for 'SoftwareVersion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SoftwareVersionIntegrationTest.testFindSoftwareVersion() {
        SoftwareVersion obj = dod.getRandomSoftwareVersion();
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to provide an identifier", id);
        obj = SoftwareVersion.findSoftwareVersion(id);
        Assert.assertNotNull("Find method for 'SoftwareVersion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SoftwareVersion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SoftwareVersionIntegrationTest.testFindAllSoftwareVersions() {
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to initialize correctly", dod.getRandomSoftwareVersion());
        long count = SoftwareVersion.countSoftwareVersions();
        Assert.assertTrue("Too expensive to perform a find all test for 'SoftwareVersion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SoftwareVersion> result = SoftwareVersion.findAllSoftwareVersions();
        Assert.assertNotNull("Find all method for 'SoftwareVersion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SoftwareVersion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SoftwareVersionIntegrationTest.testFindSoftwareVersionEntries() {
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to initialize correctly", dod.getRandomSoftwareVersion());
        long count = SoftwareVersion.countSoftwareVersions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SoftwareVersion> result = SoftwareVersion.findSoftwareVersionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SoftwareVersion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SoftwareVersion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SoftwareVersionIntegrationTest.testFlush() {
        SoftwareVersion obj = dod.getRandomSoftwareVersion();
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to provide an identifier", id);
        obj = SoftwareVersion.findSoftwareVersion(id);
        Assert.assertNotNull("Find method for 'SoftwareVersion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySoftwareVersion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SoftwareVersion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SoftwareVersionIntegrationTest.testMergeUpdate() {
        SoftwareVersion obj = dod.getRandomSoftwareVersion();
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to provide an identifier", id);
        obj = SoftwareVersion.findSoftwareVersion(id);
        boolean modified =  dod.modifySoftwareVersion(obj);
        Integer currentVersion = obj.getVersion();
        SoftwareVersion merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SoftwareVersion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SoftwareVersionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to initialize correctly", dod.getRandomSoftwareVersion());
        SoftwareVersion obj = dod.getNewTransientSoftwareVersion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SoftwareVersion' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SoftwareVersion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SoftwareVersionIntegrationTest.testRemove() {
        SoftwareVersion obj = dod.getRandomSoftwareVersion();
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SoftwareVersion' failed to provide an identifier", id);
        obj = SoftwareVersion.findSoftwareVersion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SoftwareVersion' with identifier '" + id + "'", SoftwareVersion.findSoftwareVersion(id));
    }
    
}
